spring.application.name=payment-service
server.port=8085

spring.data.mongodb.uri=mongodb://localhost:27017/payment_db

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Razorpay Config
razorpay.api.key=rzp_test_SlFwK7GFHdkbMd
razorpay.api.secret=KdKh5yqTCiCcXIRa27daP1fJ